import Header from '@/components/Header';
import Footer from '@/components/Footer';
import SectionTitle from '@/components/SectionTitle';
import {ServiceCard,ProjectCard} from '@/components/Cards';
import {stats, themes} from '@/lib/data';
import {prisma,ensureSeeded,parseJsonArray} from '@/lib/db';

const sectors=['Government Schools','Anganwadi Centres','Public Infrastructure','Overhead Bridges','Private Sector','Corporate & Hospitality','Educational Institutions','Community Spaces'];
const reasons=[
 ['01','Execution at scale','A strong artist team built to coordinate large walls, multiple locations and demanding timelines.'],
 ['02','Purpose before paint','Every mural starts with the space, audience, message and visual story — not a generic template.'],
 ['03','Quality with consistency','Clear artwork direction, artist allocation, on-site coordination and finishing checks keep the output consistent.'],
 ['04','From idea to handover','Concept, wall planning, artwork, execution, detailing and final presentation are managed as one workflow.']
];
const process=[['01','DISCOVER','Understand the space, audience, objective and wall conditions.'],['02','DESIGN','Build the visual story, composition, colour system and wall-wise plan.'],['03','EXECUTE','Deploy the artist team and bring the artwork to life on site.'],['04','DELIVER','Detail, inspect, document and hand over a finished visual environment.']];

export default async function Home(){await ensureSeeded(); const dbServices=await prisma.service.findMany({orderBy:{number:'asc'},take:6}); const dbProjects=await prisma.project.findMany({orderBy:{createdAt:'desc'},take:6}); const services=dbServices.map(s=>({...s,tags:parseJsonArray(s.tags),deliverables:parseJsonArray(s.deliverables)})); const projects=dbProjects.map(p=>({...p,scope:parseJsonArray(p.scope)})); return <><Header/><main>
<section className="hero"><div className="hero-orbit orbit-a"/><div className="hero-orbit orbit-b"/><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="dot"/> COMMERCIAL ART • EDUCATIONAL SPACES • LARGE-SCALE EXECUTION</div><h1>WE TURN <em>WALLS</em><br/>INTO <span>STORIES.</span></h1><p>VIRVAANI ART creates educational murals, public art and commercial visual experiences that turn ordinary architecture into memorable spaces.</p><div className="actions"><a className="btn dark" href="/projects">Explore Our Art ↗</a><a className="btn outline" href="/contact">Start a Project</a></div><div className="hero-stats">{stats.slice(0,3).map(s=><div key={s.label}><b>{s.value}</b><small>{s.label}</small></div>)}</div></div><div className="hero-visual"><div className="hero-frame"><img src={'/images/selected-modern-01.jpg'} alt="Large scale public bridge mural reference"/><div className="frame-overlay"/><div className="hero-label"><span>FEATURED VISUAL</span><b>PUBLIC ART × INFRASTRUCTURE</b><small>Bridge / civic mural direction</small></div></div><div className="floating-note"><span>01</span><div><b>ART IN MOTION</b><small>Concept → Artwork → Execution</small></div></div></div></div><div className="hero-scroll">SCROLL <span>↓</span></div></section>
<div className="ticker"><div>EDUCATE • INSPIRE • TRANSFORM • CREATE • PUBLIC ART • LARGE SCALE • COMMERCIAL • EDUCATIONAL •</div></div>

<section className="section intro"><div className="container story-grid"><div><SectionTitle eyebrow="01 / About VIRVAANI ART" title="WHY VIRVAANI ART STANDS OUT." desc="VIRVAANI ART specializes in commercial art and creative visual solutions for educational institutions, public spaces and private-sector projects."/><p className="body-copy">From government schools and Anganwadi centres to overhead bridges and private-sector spaces, the company combines visual storytelling with disciplined large-scale execution. The team has completed approximately <strong>150 art projects in a single district</strong> and has expanded operations across <strong>40+ districts</strong>.</p><p className="body-copy">The real strength is the ability to take a visual idea and turn it into a finished wall through a skilled, coordinated artist team — while maintaining creativity, quality and consistency at scale.</p><a className="btn dark" href="/about">Discover VIRVAANI ↗</a></div><div className="story-collage"><div className="collage-main"><img src={'/images/selected-modern-02.jpg'} alt="Large scale mural on architecture"/></div><div className="collage-small"><img src={'/images/selected-modern-03.jpg'} alt="Educational wall art"/><span>VISUAL LEARNING</span></div><div className="collage-stamp"><b>40+</b><small>districts reached</small></div></div></div></section>

<section className="stats"><div className="container stat-grid">{stats.map((s,i)=><div key={s.label}><span>0{i+1}</span><b>{s.value}</b><small>{s.label}</small></div>)}</div></section>

<section className="section why-section"><div className="container"><div className="split-title"><SectionTitle eyebrow="02 / Why VIRVAANI ART" title="CREATIVITY IS ONLY HALF THE JOB." desc="The other half is execution — the people, planning and quality discipline needed to deliver large art programmes properly."/><a className="btn outline" href="/about">Our Story ↗</a></div><div className="reason-grid">{reasons.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>

<section className="section soft"><div className="container"><div className="split-title"><SectionTitle eyebrow="03 / What We Create" title="CREATIVE SOLUTIONS FOR REAL SPACES." desc="From one classroom wall to a multi-location art programme, every concept is designed around the space and its purpose."/><a className="btn outline" href="/services">All Services ↗</a></div><div className="cards-grid">{services.slice(0,6).map(s=><ServiceCard key={s.id} s={s}/>)}</div></div></section>

<section className="scale-band"><div className="container scale-grid"><div className="scale-image"><img src={'/images/wildlife-corridor.jpg'} alt="Public bridge mural artwork"/><div><span>PUBLIC ART</span><b>MAKE INFRASTRUCTURE MEMORABLE.</b></div></div><div><span className="eyebrow">04 / Built for scale</span><h2>BIG WALLS.<br/><em>BIGGER IMPACT.</em></h2><p>VIRVAANI ART is designed for projects where artwork has to work at architectural scale — bridges, facades, campuses, corridors and public circulation spaces.</p><div className="mini-metrics"><div><b>150+</b><span>projects in one district</span></div><div><b>40+</b><span>district reach</span></div><div><b>09</b><span>art capabilities</span></div></div><a className="btn dark" href="/projects">See the Work ↗</a></div></div></section>

<section className="section projects-section"><div className="container"><div className="split-title"><SectionTitle eyebrow="05 / Selected Work" title="WALLS WITH A PURPOSE." desc="Real-world art references across educational, public, community and commercial environments."/><a className="btn outline" href="/projects">View All Projects ↗</a></div><div className="projects-grid">{projects.slice(0,6).map(p=><ProjectCard key={p.id} p={p}/>)}</div></div></section>

<section className="section process-section"><div className="container"><SectionTitle eyebrow="06 / How We Work" title="FROM BLANK WALL TO FINISHED EXPERIENCE." desc="A clear process keeps creative ambition and execution discipline moving together."/><div className="process-grid">{process.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>

<section className="section sectors-section"><div className="container"><SectionTitle eyebrow="07 / Where We Work" title="BUILT FOR DIFFERENT KINDS OF SPACES." desc="Our art programmes can be adapted to the scale, audience and visual identity of each environment."/><div className="sector-list">{sectors.map((s,i)=><a href="/services" key={s}><span>0{i+1}</span><b>{s}</b><i>↗</i></a>)}</div></div></section>

<section className="experience-band"><div className="container experience-grid"><div><span className="eyebrow">08 / Signature Experience</span><h2>EVERY WALL<br/>HAS A <i>STORY.</i></h2><p>We don't just paint walls. We build visual environments that teach, inspire, guide and create identity.</p><a className="btn light-btn" href="/contact">Start Your Wall Story ↗</a></div><div className="experience-image"><img src={'/images/geometric-atrium.jpg'} alt="Commercial mural environment"/><div><b>01—04</b><span>IDEA → DESIGN → ART → DELIVERY</span></div></div></div></section>

<section className="section themes-section"><div className="container"><SectionTitle eyebrow="09 / Explore Themes" title="CHOOSE A WORLD TO BRING TO LIFE." desc="Research-led mural directions inspired by learning, identity, culture, public space and commercial environments."/><div className="theme-grid">{themes.map((t,i)=><a href="/gallery" key={t.name} className="theme-card"><img src={t.image} alt={t.name}/><div><span>0{i+1}</span><b>{t.name}</b><small>{t.desc}</small></div></a>)}</div></div></section>

<section className="cta"><div className="container cta-inner"><div><span className="eyebrow">10 / Ready to transform a space?</span><h2>LET'S CREATE<br/><em>SOMETHING EXTRAORDINARY.</em></h2><p>Tell us about your school, institution, public space or commercial project and the VIRVAANI ART team can take it from idea to finished wall.</p></div><a className="circle-cta" href="/contact">Start<br/>a Project <span>↗</span></a></div></section>
</main><Footer/></>}
