export type Service = { id:string; title:string; short:string; image:string; tags:string[]; number:string; detail:string; deliverables:string[] };
export type Project = { id:string; title:string; sector:string; location:string; image:string; summary:string; year:string; detail:string; scope:string[] };


export const services: Service[] = [
 {id:'educational-murals',number:'01',title:'3D Educational Wall Painting',short:'Immersive subject-led murals that turn blank walls into visual learning tools.',image:'/images/world-map-classroom.jpg',tags:['3D Art','STEM','Schools'],detail:'Concept-led educational walls that make science, mathematics, geography and discovery easier to understand through large-format visual storytelling.',deliverables:['Theme research & concept direction','Wall-wise artwork layout','3D / perspective visual treatment','On-site artist execution','Final finishing & quality review']},
 {id:'classroom-art',number:'02',title:'Classroom Wall Painting',short:'Age-appropriate scenes, colour systems and storytelling for everyday classrooms.',image:'/images/creative-room.jpg',tags:['Classrooms','Kids','Learning'],detail:'Classroom artwork designed around the age group, curriculum context, available wall area and the visual energy of the room.',deliverables:['Classroom theme planning','Age-appropriate illustrations','Colour & composition planning','On-site painting','Touch-up and handover']},
 {id:'educational-murals-2',number:'03',title:'Educational Murals',short:'Large-format murals for libraries, corridors, campuses and institutional spaces.',image:'/images/library-story.jpg',tags:['Murals','Libraries','Campus'],detail:'Large educational murals that convert libraries, corridors and shared spaces into memorable visual environments.',deliverables:['Story / subject mapping','Large-format artwork','Surface preparation guidance','Artist team execution','Finishing & documentation']},
 {id:'school-wall-art',number:'04',title:'School Wall Art',short:'Complete visual programs from concept and artwork direction to on-site execution.',image:'/images/school-compound.jpg',tags:['Schools','Campaigns','Execution'],detail:'A complete school visual identity program combining multiple walls, themes and outdoor zones into one coherent experience.',deliverables:['Campus visual audit','Wall-by-wall concepts','Theme consistency system','Multi-artist execution','Final quality inspection']},
 {id:'anganwadi',number:'05',title:'Anganwadi & Community Art',short:'Friendly, colourful environments designed around early learning and community use.',image:'/images/selected-modern-03.jpg',tags:['Anganwadi','Community','Nature'],detail:'Warm, approachable artwork for early-learning and community spaces, with simple visual language and positive storytelling.',deliverables:['Early-learning theme selection','Friendly character / nature artwork','Interior & exterior wall concepts','Artist execution','Final clean-up & handover']},
 {id:'public-art',number:'06',title:'Public Space & Bridge Art',short:'High-impact civic artwork for overhead bridges, facades and public circulation zones.',image:'/images/selected-modern-01.jpg',tags:['Public','Bridges','Civic','Geo India reference'],detail:'Large-scale public artwork that gives bridges, facades and civic spaces a stronger visual identity while staying practical for high-traffic locations.',deliverables:['Site measurement & visual planning','Public-facing concept design','Large-format execution','Multi-zone coordination','Finishing & inspection']},
 {id:'commercial',number:'07',title:'Private Sector Creative Art',short:'Distinctive visual installations for private-sector spaces, offices, hospitality and brands.',image:'/images/selected-modern-02.jpg',tags:['Commercial','Branding','Interiors'],detail:'Custom art environments for offices, retail, hospitality and private-sector spaces where the artwork becomes part of the brand experience.',deliverables:['Brand / space understanding','Creative concept options','Material & finish planning','Artist-led execution','Final presentation']},
 {id:'large-scale',number:'08',title:'Large Scale Art Execution',short:'Artist-led multi-location execution built for consistency, quality and deadlines.',image:'/images/geometric-atrium.jpg',tags:['Multi-site','Team','Quality'],detail:'A structured execution capability for large and multi-location art programs, supported by an experienced artist team and consistent visual direction.',deliverables:['Execution planning','Artist allocation','Daily quality coordination','Multi-location consistency','Completion tracking']},
 {id:'communication-art',number:'09',title:'Communication & Awareness Art',short:'Visual storytelling that communicates messages clearly across public and institutional spaces.',image:'/images/nature-water-cycle.jpg',tags:['Awareness','Messaging','Public'],detail:'Purpose-driven wall artwork for awareness campaigns, public information, social themes and community communication.',deliverables:['Message and audience mapping','Visual communication concept','Wall-wise composition','On-site execution','Final review and documentation']}
];

export const projects: Project[] = [
 {id:'space-learning',title:'Learning Facade Intervention',sector:'Educational Institution',location:'India',image:'/images/world-map-classroom.jpg',summary:'A real-world reference for turning educational architecture into a visual learning surface.',year:'2026',detail:'A learning-led wall treatment where maps, educational writing and architecture work together to make the built environment part of the lesson.',scope:['Theme & subject mapping','Wall composition','Educational visual system','Artist execution','Final detailing']},
 {id:'school-compound',title:'School Mural Installation',sector:'Institutional Art',location:'India',image:'/images/school-compound.jpg',summary:'A bold mural intervention showing how large walls can become visual landmarks.',year:'2026',detail:'A reference direction for high-visibility institutional walls where colour, storytelling and scale need to work together.',scope:['Visual direction','Large-format artwork','Execution coordination','Surface finishing','Documentation']},
 {id:'world-map',title:'World Discovery Wall',sector:'Educational Space',location:'India',image:'/images/learning-stairs.jpg',summary:'Narrative wall art that turns a circulation space into a place for learning and discovery.',year:'2026',detail:'A large narrative mural reference demonstrating how history, identity and storytelling can live directly on architecture.',scope:['Narrative theme','Illustration system','Wall layout','Hand-painted execution','Final detailing']},
 {id:'library',title:'Community Story Wall',sector:'Public / Community',location:'India',image:'/images/library-story.jpg',summary:'A colourful public-wall reference combining place, people and visual identity.',year:'2026',detail:'A community-facing artwork direction designed to make everyday public surfaces more memorable and welcoming.',scope:['Community theme','Artwork direction','Wall preparation','Artist execution','Finishing']},
 {id:'science-lab',title:'Science & Innovation Wall',sector:'Science / Institutional',location:'India',image:'/images/science-lab.jpg',summary:'A science-themed visual reference connecting technical identity with public-facing art.',year:'2026',detail:'A technology and science visual direction suitable for schools, labs, institutions and innovation-focused spaces.',scope:['Science theme','Visual storytelling','Large-format artwork','Execution','Quality review']},
 {id:'nature',title:'Community Nature Wall',sector:'Public Space',location:'India',image:'/images/nature-water-cycle.jpg',summary:'A culturally rooted wall-art reference that brings colour and identity into everyday surroundings.',year:'2026',detail:'A community artwork direction showing how local visual language can create a stronger sense of place.',scope:['Local theme research','Artwork development','Wall painting','Detail finishing','Handover']},
 {id:'atrium',title:'Commercial Mural Environment',sector:'Private Sector',location:'India',image:'/images/selected-modern-02.jpg',summary:'A commercial interior where the mural becomes part of the customer experience.',year:'2026',detail:'A reference for private-sector environments where artwork can reinforce atmosphere, identity and memorable spatial experience.',scope:['Brand / space alignment','Concept options','Artwork production','On-site execution','Final styling']},
 {id:'wildlife',title:'Large Scale Urban Art',sector:'Public Art',location:'India',image:'/images/selected-modern-01.jpg',summary:'A building-scale artwork reference demonstrating the impact of monumental public art.',year:'2026',detail:'A large architectural surface transformed into a visual landmark — the kind of scale VIRVAANI ART can plan and execute for major programmes.',scope:['Site-scale concept','Large-format artwork','Artist team planning','Execution management','Final quality check']},
 {id:'artist-process',title:'Artist At Work',sector:'Execution',location:'India',image:'/images/space-corridor.jpg',summary:'A process-led reference that puts the artist and execution craft at the centre.',year:'2026',detail:'A visual reminder that the final wall is only the outcome; disciplined artist execution is what turns the concept into a finished space.',scope:['Artist planning','On-site execution','Detailing','Quality control','Visual documentation']},
 {id:'bridge-identity',title:'Civic Bridge Identity',sector:'Public Infrastructure',location:'India',image:'/images/geometric-atrium.jpg',summary:'A bold public-art direction for high-visibility bridge and civic circulation spaces.',year:'2026',detail:'A public-facing art concept designed for high-visibility infrastructure where colour, movement and identity need to work at large scale.',scope:['Civic concept','High-visibility composition','Large-scale execution','Site coordination','Finishing']},
 {id:'community-learning',title:'Anganwadi & Early Learning',sector:'Anganwadi / Community',location:'Assam, India',image:'/images/selected-modern-03.jpg',summary:'A real Anganwadi centre reference that grounds the service in the Indian community-learning context.',year:'2026',detail:'A service reference for early-learning centres where artwork should feel friendly, durable, welcoming and easy for children to understand.',scope:['Early-learning theme','Exterior / interior wall planning','Child-friendly artwork','Execution','Handover']},
 {id:'commercial-identity',title:'Heritage & Commercial Mural',sector:'Private / Commercial',location:'Odisha, India',image:'/images/creative-room.jpg',summary:'A hand-painted mural reference showing how craft and architecture can work together.',year:'2026',detail:'A visual direction for private spaces that want something more distinctive than standard decorative graphics.',scope:['Space study','Creative concept','Artwork production','Painting execution','Final presentation']}
];

export const themes = [
 {name:'Space & Science',image:'/images/science-lab.jpg',desc:'Astronomy, STEM, discovery',detail:'Galaxy, planets, scientific symbols and discovery-led visual stories.'},
 {name:'Nature & Environment',image:'/images/nature-water-cycle.jpg',desc:'Water, ecology, greenery',detail:'Water cycles, plants, ecology and environmental awareness.'},
 {name:'India & Culture',image:'/images/selected-modern-01.jpg',desc:'Identity, community, heritage',detail:'Local identity, culture, community stories and heritage-inspired visual language.'},
 {name:'World & Geography',image:'/images/world-map-classroom.jpg',desc:'Maps, places, exploration',detail:'Maps, continents, landmarks and exploration themes for geography-led learning.'},
 {name:'Public Art & Identity',image:'/images/school-compound.jpg',desc:'Bridges, facades, civic spaces',detail:'High-visibility public artwork for infrastructure and shared civic environments.'},
 {name:'Commercial & Brand Spaces',image:'/images/selected-modern-02.jpg',desc:'Offices, retail, hospitality',detail:'Contemporary murals and visual environments for private-sector spaces.'}
];

export const stats = [
 {value:'150+',label:'art projects completed in one district'},
 {value:'40+',label:'districts reached through expanded operations'},
 {value:'09',label:'commercial art capabilities'},
 {value:'1 TEAM',label:'artist-led execution from concept to handover'}
];
